### 用户登录
POST http://localhost:8081/login HTTP/1.1
content-type: application/json

{
    "email": "abc@abc.com",
    "password": "abc"
}

### 用户注册
POST http://localhost:8081/register HTTP/1.1
content-type: application/json

{
    "email": "biubiu0_0@163.com",
    "password": "123456",
    "mobile": "17620304992"
}

### 获取任务
GET http://localhost:8081/tasks/myTasks HTTP/1.1
content-type: application/json

### 创建任务
POST http://localhost:8081/tasks/

{
    "name": "task01",
    "description": "task01task01task01",
    "steps":[{},{}]
}

### 获取原型列表
GET http://localhost:8081/user/ptts